```{r}
library(data.table)
library(datasets)
data("cars")
fit1 <- lm(dist~speed-1, cars)
fit2 <- glm(dist~speed + I(speed^2) -1, data=cars)
cutspeed <- 20
d1 <- as.data.frame(cbind(cars,speedsp=ifelse(cars$speed > cutspeed, cars$speed - cutspeed, 0 )))
fit4 <- lm(dist~speedsp+speed-1, data=d1)

x <- seq(0,30,by=0.1)
y <- fit1$coefficients[1]*x
f1 <- as.data.frame(cbind(x,y))

x <- seq(0,30,by=0.1)
y <- fit2$coefficients[2]*x^2 + fit2$coefficients[1]*x
f2 <- as.data.frame(cbind(x,y))

x <- seq(0,30,by=0.1)
x2 <- ifelse(x > cutspeed, x - cutspeed, 0 )
y <- fit4$coefficients[2]*x + fit4$coefficients[1]*x2
f4 <- as.data.frame(cbind(x,y))

xint <- 27.5
ndat <- as.data.frame(xint)
colnames(ndat) <- "speed"
yint1 <- predict(fit1, newdata = ndat)
yint2 <- predict(fit2, newdata = ndat)
ndat <- as.data.frame(cbind(xint,ifelse(xint > cutspeed, xint - cutspeed, 0 )))
colnames(ndat) <- c("speed","speedsp")
yint4 <- predict(fit4, newdata = ndat)

plot <- ggplot() +
     geom_point(data=cars, aes(x=speed,y=dist),alpha=1) +
     coord_cartesian(xlim=c(0,30),ylim=c(0,130)) +
     geom_line(data=f1,aes(x=x,y=y), color="black", size=1) +
     geom_line(data=f2,aes(x=x,y=y), color="red", size=1) +
     geom_line(data=f4,aes(x=x,y=y), color="blue", size=1) +
     geom_vline(xintercept = xint, size=1) +
     geom_hline(yintercept = yint1, linetype=2, color="black", size=1) +
     geom_hline(yintercept = yint2, linetype=2, color="red", size=1) +
     geom_hline(yintercept = yint4, linetype=2, color="blue", size=1) +
     labs(x="Speed/Miles per Hour", y="Stopping Distance/Feet") +
     scale_x_continuous(breaks = seq(0,30,by=2)) +
     scale_y_continuous(breaks = seq(0,150,by=10)) +
     theme_classic() + theme(legend.position = "none")
plot
```


```{r}
ggplotly(plot)
```


